import { University, ProcedureFlow, Payment, Content, ProcedureFlowDetail, ProcedureStepWithProgress } from './types';

// サンプル大学データ（20校）
export const sampleUniversities: University[] = [
  {
    id: 1,
    code: 'UNIV001',
    name: 'サンプル大学',
    description: 'サンプル大学の説明です。この大学は教育と研究に力を入れています。',
    domain: 'sample-univ.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    code: 'UNIV002',
    name: 'テクノロジー大学',
    description: '最新のテクノロジーを学ぶことができる大学です。',
    domain: 'tech-univ.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    code: 'UNIV003',
    name: 'リベラルアーツ大学',
    description: '幅広い教養を身につけることができる大学です。',
    domain: 'liberal-arts-univ.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 4,
    code: 'UNIV004',
    name: '国際ビジネス大学',
    description: 'グローバルな視点でビジネスを学ぶことができる大学です。',
    domain: 'international-business.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 5,
    code: 'UNIV005',
    name: '医療保健大学',
    description: '医療と保健の専門知識を学ぶことができる大学です。',
    domain: 'medical-health.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 6,
    code: 'UNIV006',
    name: '芸術デザイン大学',
    description: '創造性と表現力を育む芸術・デザインの大学です。',
    domain: 'art-design.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 7,
    code: 'UNIV007',
    name: '環境科学大学',
    description: '環境問題に取り組む科学者を育成する大学です。',
    domain: 'environmental-science.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 8,
    code: 'UNIV008',
    name: '教育大学',
    description: '優れた教育者を育成することを目的とした大学です。',
    domain: 'education-univ.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 9,
    code: 'UNIV009',
    name: '工科大学',
    description: '実践的な工学技術を学ぶことができる大学です。',
    domain: 'engineering-tech.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 10,
    code: 'UNIV010',
    name: '経済経営大学',
    description: '経済と経営の専門知識を学ぶことができる大学です。',
    domain: 'economics-management.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 11,
    code: 'UNIV011',
    name: '法学大学',
    description: '法律の専門知識と法的思考力を養う大学です。',
    domain: 'law-univ.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 12,
    code: 'UNIV012',
    name: '農学大学',
    description: '農業と生命科学の研究に取り組む大学です。',
    domain: 'agriculture-univ.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 13,
    code: 'UNIV013',
    name: '情報科学大学',
    description: '情報技術とコンピュータサイエンスを学ぶ大学です。',
    domain: 'information-science.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 14,
    code: 'UNIV014',
    name: '看護大学',
    description: '看護の専門知識と実践力を養う大学です。',
    domain: 'nursing-univ.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 15,
    code: 'UNIV015',
    name: 'スポーツ科学大学',
    description: 'スポーツと健康科学を学ぶことができる大学です。',
    domain: 'sports-science.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 16,
    code: 'UNIV016',
    name: '外国語大学',
    description: '多様な言語と文化を学ぶことができる大学です。',
    domain: 'foreign-languages.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 17,
    code: 'UNIV017',
    name: '音楽大学',
    description: '音楽の専門知識と演奏技術を学ぶ大学です。',
    domain: 'music-univ.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 18,
    code: 'UNIV018',
    name: '薬学大学',
    description: '薬学と医療の専門知識を学ぶことができる大学です。',
    domain: 'pharmacy-univ.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 19,
    code: 'UNIV019',
    name: '建築大学',
    description: '建築と都市計画を学ぶことができる大学です。',
    domain: 'architecture-univ.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 20,
    code: 'UNIV020',
    name: '海洋科学大学',
    description: '海洋と水産の研究に取り組む大学です。',
    domain: 'marine-science.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// サンプル手続きフローデータ
// 各大学に対して入学手続きフローと卒業手続きフローを作成
export const sampleProcedureFlows: ProcedureFlow[] = (() => {
  const flows: ProcedureFlow[] = [];
  
  // 各大学（1-20）に対して入学手続きフローと卒業手続きフローを作成
  for (let univId = 1; univId <= 20; univId++) {
    // 入学手続きフロー
    flows.push({
      id: univId * 2 - 1,
      universityId: univId,
      name: '入学手続きフロー',
      description: '新入生向けの入学手続きフローです。',
      flowType: '入学',
      displayOrder: 1,
      active: true,
      steps: [
        {
          id: (univId * 2 - 1) * 10 + 1,
          flowId: univId * 2 - 1,
          contentId: 1,
          name: '入学願書の提出',
          description: '入学願書を提出してください',
          stepOrder: 1,
          isRequired: true,
          active: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
        {
          id: (univId * 2 - 1) * 10 + 2,
          flowId: univId * 2 - 1,
          contentId: 2,
          name: '入学検定料の納付',
          description: '入学検定料を納付してください',
          stepOrder: 2,
          isRequired: true,
          active: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
        {
          id: (univId * 2 - 1) * 10 + 3,
          flowId: univId * 2 - 1,
          contentId: 3,
          name: '入学金の納付',
          description: '入学金を納付してください',
          stepOrder: 3,
          isRequired: true,
          active: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });

    // 卒業手続きフロー
    flows.push({
      id: univId * 2,
      universityId: univId,
      name: '卒業手続きフロー',
      description: '卒業予定者向けの手続きフローです。',
      flowType: '卒業',
      displayOrder: 2,
      active: true,
      steps: [
        {
          id: (univId * 2) * 10 + 1,
          flowId: univId * 2,
          contentId: 1,
          name: '卒業論文の提出',
          description: '卒業論文を提出してください',
          stepOrder: 1,
          isRequired: true,
          active: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
        {
          id: (univId * 2) * 10 + 2,
          flowId: univId * 2,
          contentId: 2,
          name: '卒業手続き書類の提出',
          description: '卒業手続きに必要な書類を提出してください',
          stepOrder: 2,
          isRequired: true,
          active: true,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    });
  }
  
  return flows;
})();

// サンプル支払いデータ
export const samplePayments: Payment[] = [
  {
    id: 1,
    userId: 1,
    universityId: 1,
    flowId: 1,
    paymentType: '入学金',
    amount: 300000,
    currency: 'JPY',
    status: 'PENDING',
    paymentMethod: '銀行振込',
    notes: '入学手続きに伴う入学金です',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    userId: 1,
    universityId: 1,
    flowId: 1,
    paymentType: '入学検定料',
    amount: 35000,
    currency: 'JPY',
    status: 'COMPLETED',
    paymentMethod: 'クレジットカード',
    paidAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    notes: '入学検定料の支払いが完了しました',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    userId: 1,
    universityId: 2,
    flowId: 2,
    paymentType: '授業料（前期）',
    amount: 500000,
    currency: 'JPY',
    status: 'PROCESSING',
    paymentMethod: '銀行振込',
    notes: '前期授業料の支払い処理中です',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// サンプルコンテンツデータ
export const sampleContents: Content[] = [
  {
    id: 1,
    title: '入学手続きガイド',
    body: '入学手続きの詳細なガイドです。',
    slug: 'admission-guide',
    status: 'PUBLISHED',
    authorId: 1,
    universityId: 1,
    contentType: '入学手続き',
    metaDescription: '入学手続きの詳細なガイドです。',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 2,
    title: '新入生向けオリエンテーション',
    body: '新入生向けオリエンテーションの詳細情報です。',
    slug: 'orientation',
    status: 'PUBLISHED',
    authorId: 1,
    universityId: 1,
    contentType: 'お知らせ',
    metaDescription: '新入生向けオリエンテーションの詳細情報です。',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 3,
    title: 'よくある質問（FAQ）',
    body: 'よくある質問と回答をまとめました。',
    slug: 'faq',
    status: 'PUBLISHED',
    authorId: 1,
    universityId: 2,
    contentType: 'FAQ',
    metaDescription: 'よくある質問と回答をまとめました。',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
];

// サンプル手続きフロー詳細データを作成する関数
export const createSampleProcedureFlowDetail = (flowId: number, universityId: number): ProcedureFlowDetail | null => {
  const flow = sampleProcedureFlows.find(f => f.id === flowId && f.universityId === universityId);
  if (!flow) return null;

  const stepsWithProgress: ProcedureStepWithProgress[] = (flow.steps || []).map((step, index) => ({
    ...step,
    progressStatus: 'NOT_STARTED' as const,
    canStart: true, // すべてのステップを開始可能にする（依存関係のチェックは別途実装）
  }));

  const totalSteps = stepsWithProgress.length;
  const completedSteps = stepsWithProgress.filter(s => s.progressStatus === 'COMPLETED').length;
  const inProgressSteps = stepsWithProgress.filter(s => s.progressStatus === 'IN_PROGRESS').length;
  const notStartedSteps = stepsWithProgress.filter(s => s.progressStatus === 'NOT_STARTED').length;
  const completionRate = totalSteps > 0 ? (completedSteps / totalSteps) * 100 : 0;

  return {
    id: flow.id,
    universityId: flow.universityId,
    name: flow.name,
    description: flow.description,
    flowType: flow.flowType,
    displayOrder: flow.displayOrder,
    active: flow.active,
    steps: stepsWithProgress,
    totalSteps,
    completedSteps,
    inProgressSteps,
    notStartedSteps,
    completionRate,
    createdAt: flow.createdAt,
    updatedAt: flow.updatedAt,
  };
};

