import { University, ProcedureFlow, Payment, Content } from './types';

// サンプル大学データ
export const sampleUniversities: University[] = [
  {
    id: 1,
    code: 'UNIV001',
    name: 'サンプル大学',
    description: 'サンプル大学の説明です。この大学は教育と研究に力を入れています。',
    domain: 'sample-univ.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    code: 'UNIV002',
    name: 'テクノロジー大学',
    description: '最新のテクノロジーを学ぶことができる大学です。',
    domain: 'tech-univ.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    code: 'UNIV003',
    name: 'リベラルアーツ大学',
    description: '幅広い教養を身につけることができる大学です。',
    domain: 'liberal-arts-univ.ac.jp',
    active: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// サンプル手続きフローデータ
export const sampleProcedureFlows: ProcedureFlow[] = [
  {
    id: 1,
    universityId: 1,
    name: '入学手続きフロー',
    description: '新入生向けの入学手続きフローです。',
    flowType: '入学',
    displayOrder: 1,
    active: true,
    steps: [
      {
        id: 1,
        flowId: 1,
        contentId: 1,
        name: '入学願書の提出',
        description: '入学願書を提出してください',
        stepOrder: 1,
        isRequired: true,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 2,
        flowId: 1,
        contentId: 2,
        name: '入学検定料の納付',
        description: '入学検定料を納付してください',
        stepOrder: 2,
        isRequired: true,
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    universityId: 1,
    name: '卒業手続きフロー',
    description: '卒業予定者向けの手続きフローです。',
    flowType: '卒業',
    displayOrder: 2,
    active: true,
    steps: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// サンプル支払いデータ
export const samplePayments: Payment[] = [
  {
    id: 1,
    userId: 1,
    universityId: 1,
    flowId: 1,
    paymentType: '入学金',
    amount: 300000,
    currency: 'JPY',
    status: 'PENDING',
    paymentMethod: '銀行振込',
    notes: '入学手続きに伴う入学金です',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    userId: 1,
    universityId: 1,
    flowId: 1,
    paymentType: '入学検定料',
    amount: 35000,
    currency: 'JPY',
    status: 'COMPLETED',
    paymentMethod: 'クレジットカード',
    paidAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    notes: '入学検定料の支払いが完了しました',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    userId: 1,
    universityId: 2,
    flowId: 2,
    paymentType: '授業料（前期）',
    amount: 500000,
    currency: 'JPY',
    status: 'PROCESSING',
    paymentMethod: '銀行振込',
    notes: '前期授業料の支払い処理中です',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// サンプルコンテンツデータ
export const sampleContents: Content[] = [
  {
    id: 1,
    title: '入学手続きガイド',
    body: '入学手続きの詳細なガイドです。',
    slug: 'admission-guide',
    status: 'PUBLISHED',
    authorId: 1,
    universityId: 1,
    contentType: '入学手続き',
    metaDescription: '入学手続きの詳細なガイドです。',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 2,
    title: '新入生向けオリエンテーション',
    body: '新入生向けオリエンテーションの詳細情報です。',
    slug: 'orientation',
    status: 'PUBLISHED',
    authorId: 1,
    universityId: 1,
    contentType: 'お知らせ',
    metaDescription: '新入生向けオリエンテーションの詳細情報です。',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
  {
    id: 3,
    title: 'よくある質問（FAQ）',
    body: 'よくある質問と回答をまとめました。',
    slug: 'faq',
    status: 'PUBLISHED',
    authorId: 1,
    universityId: 2,
    contentType: 'FAQ',
    metaDescription: 'よくある質問と回答をまとめました。',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    publishedAt: new Date().toISOString(),
  },
];

